services:
  - type: web
    name: trueval-api
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: AIRTABLE_API_KEY
        value: your_airtable_api_key
